type Language = "en" | "sv" | "fa";
const prices = [[3500,6000],[7500,14000],[12000,22000],[18000,32000],[6500,15000],[500,500]];
const names = ["Essential", "Business", "Multilingual", "Online Store", "AI Starter", "Consultation"];
const concepts = ["Nord Bloom", "Luma Studio", "Saffron Table", "KindPath", "Founder Desk"];
const content = {
  en: {
    label: "SWEDEN-BASED • HUMAN-LED", title: "A thoughtful start. An accessible price.", intro: "Focused digital services for small businesses. Start with the essentials and expand when you are ready. These are indicative ranges for the scope below, not a binding quote.",
    scopes: ["One-page, single-language website with a contact form and two revision rounds. Content supplied by you.", "Up to five pages in one language, basic search metadata and two revision rounds. Content supplied by you.", "Up to five pages in three languages with right-to-left support. Translations supplied by you; two revision rounds.", "Store on an existing commerce platform, up to 20 supplied products and one standard payment integration. Two revision rounds; custom commerce excluded.", "One limited FAQ assistant or one simple automation. Feasibility review and agreed usage limits before work begins; two revision rounds.", "One hour to review your needs and recommend practical next steps."],
    unit: "per hour", guide: "USD figures are illustrative, rounded at 1 USD ≈ 10 SEK; they are not a live exchange-rate feed. SEK is the base currency. These business service prices exclude applicable taxes. Your quote shows taxes and the full payable total.", cta: "Request a clear estimate", terms: "Clarity before commitment", rules: [
      ["Before you sign", "Your written quote is valid for 14 days. Within that period, the quoted scope and fee remain available. If you request scope changes, new technical requirements emerge, or the quote expires, we explain any adjustment and issue a replacement quote for your approval before you commit."],
      ["After you accept", "The agreed fee stays fixed for the agreed scope, including when exchange rates change. Extra work starts only after you approve its price and timeline in writing. The contract confirms deliverables, revision rounds, currency and payment milestones."],
      ["Every cost explained", "Domains, hosting, platform subscriptions, AI/API usage, paid assets and translation are separate unless expressly included. Recurring charges and payment-provider fees are identified before acceptance. No new ELORNA charge is added without your approval."],
      ["Room to start smaller", "If your budget is limited, we can explore a smaller first phase or milestone payments, subject to scope and availability. Nonprofits and community projects are welcome to ask about a tailored scope. There is no pressure to purchase more than you need."]],
    portfolio: "Concept studio", portfolioTitle: "Five directions. Real attention to detail.", disclosure: "Original fictional design studies created to illustrate possible approaches. They are not commissioned projects or working client products, and no client results are claimed.", badge: "FICTIONAL CONCEPT", preview: "Static design study", descriptions: ["A floral shop direction with occasion-based discovery, readable product cards and a considered ordering journey.", "A beauty studio direction connecting clear service descriptions, pricing and a welcoming booking journey.", "A Persian–Scandinavian restaurant direction for a three-language menu and a clear reservation path.", "A community organisation direction with readable information and a welcoming volunteer journey.", "A founder dashboard direction for tasks, enquiries and AI-assisted answers reviewed by a human."],
    mock: ["Flowers for everyday moments", "A little time for yourself", "Gather around our table", "Small actions. Shared possibility.", "Your next step, in focus"],
    feedbackTitle: "Trust grows through honest feedback.", feedbackText: "ELORNA is building its client portfolio. Verified feedback will be published with each client’s permission as projects are completed. For now, explore the labelled concepts and request a written proposal to assess our approach.", feedbackCta: "Share your experience", feedbackFoot: "Worked with ELORNA? Tell us what helped and what could improve. Publication requires your permission; positive feedback is never required.",
  },
  sv: {
    label: "BASERAT I SVERIGE • MED MÄNNISKAN I CENTRUM", title: "En genomtänkt start. Ett tillgängligt pris.", intro: "Digitala tjänster med tydlig omfattning för små företag. Börja med det viktigaste och utveckla vidare när du är redo. Priserna är vägledande intervall, inte bindande offerter.",
    scopes: ["En sida på ett språk, kontaktformulär och två korrekturomgångar. Du tillhandahåller innehållet.", "Upp till fem sidor på ett språk, grundläggande sökmetadata och två korrekturomgångar. Du tillhandahåller innehållet.", "Upp till fem sidor på tre språk med stöd för höger-till-vänster. Du tillhandahåller översättningarna. Två korrekturomgångar.", "Webbutik på en befintlig plattform med upp till 20 produkter och en standardintegration för betalning. Två korrekturomgångar; specialbyggd e-handel ingår inte.", "En avgränsad frågeassistent eller ett enkelt automatiserat flöde. Genomförbarhet och användningsgränser avtalas först. Två korrekturomgångar.", "En timme för att gå igenom dina behov och föreslå konkreta nästa steg."],
    unit: "per timme", guide: "USD-beloppen är avrundade exempel vid 1 USD ≈ 10 SEK, inte en aktuell valutakurs. SEK är basvaluta. Företagspriserna är exklusive tillämplig skatt. Offerten visar skatt och hela beloppet att betala.", cta: "Be om en tydlig offert", terms: "Tydlighet innan du bestämmer dig", rules: [
      ["Innan avtal", "Din skriftliga offert gäller i 14 dagar för angiven omfattning och pris. Om du önskar en ändring, nya tekniska krav framkommer eller giltighetstiden löper ut förklarar vi eventuella justeringar och lämnar en ny offert för godkännande innan du ingår avtal."],
      ["Efter godkännande", "Avtalat pris gäller för avtalad omfattning även om valutakursen ändras. Tilläggsarbete påbörjas först när du skriftligen godkänt pris och tidsplan. Leveranser, korrekturomgångar, valuta och betalningsetapper anges i avtalet."],
      ["Alla kostnader förklaras", "Domän, hosting, plattformsabonnemang, AI/API-användning, licensierat material och översättning tillkommer om de inte uttryckligen ingår. Löpande kostnader och betalningsavgifter anges före godkännande. Nya avgifter från ELORNA kräver ditt godkännande."],
      ["Möjlighet att börja mindre", "Med en begränsad budget kan vi undersöka en mindre första etapp eller delbetalning per leverans, beroende på omfattning och tillgänglighet. Ideella verksamheter är välkomna att fråga om ett anpassat upplägg. Du behöver inte köpa mer än du behöver."]],
    portfolio: "Konceptstudio", portfolioTitle: "Fem riktningar. Omtanke i varje detalj.", disclosure: "Fiktiva designstudier som visar möjliga arbetssätt. De är inte kunduppdrag eller fungerande kundprodukter. Inga kundresultat påstås.", badge: "FIKTIVT KONCEPT", preview: "Statisk designstudie", descriptions: ["En blomsterbutik med tillfällesbaserad navigation, tydliga produktkort och en genomtänkt beställningsresa.", "En skönhetsstudio där tjänster, priser och en välkomnande bokningsresa möts.", "En persisk-skandinavisk restaurang med meny på tre språk och en tydlig väg till bordsbokning.", "En ideell verksamhet med lättläst information och en välkomnande resa för volontärer.", "En arbetsyta för grundare med uppgifter, förfrågningar och AI-assisterade svar med mänsklig granskning."],
    mock: ["Blommor för vardagens stunder", "En stund för dig själv", "Samlas vid vårt bord", "Små insatser. Gemensamma möjligheter.", "Ditt nästa steg i fokus"],
    feedbackTitle: "Förtroende växer genom ärlig återkoppling.", feedbackText: "ELORNA bygger sin kundportfölj. Verifierade omdömen publiceras med kundens tillstånd när uppdrag avslutas. Tills dess kan du utforska de märkta koncepten och be om en skriftlig offert för att bedöma vårt arbetssätt.", feedbackCta: "Dela din erfarenhet", feedbackFoot: "Har du arbetat med ELORNA? Berätta vad som hjälpte och vad vi kan förbättra. Publicering kräver ditt tillstånd; positiv återkoppling är aldrig ett krav.",
  },
  fa: {
    label: "فعالیت از سوئد • با محوریت انسان", title: "شروعی سنجیده، با قیمتی دست‌یافتنی", intro: "خدمات دیجیتال با محدوده روشن برای کسب‌وکارهای کوچک. از ضروریات شروع کنید و زمانی که آماده بودید توسعه دهید. این بازه‌ها راهنمای بودجه هستند و پیشنهاد قیمت قطعی محسوب نمی‌شوند.",
    scopes: ["سایت یک‌صفحه‌ای و تک‌زبانه، فرم تماس و دو دور اصلاح. محتوا را شما ارائه می‌کنید.", "تا پنج صفحه به یک زبان، تنظیمات اولیه اطلاعات موتور جست‌وجو و دو دور اصلاح. محتوا را شما ارائه می‌کنید.", "تا پنج صفحه به سه زبان با پشتیبانی راست‌به‌چپ و دو دور اصلاح. ترجمه‌ها را شما ارائه می‌کنید.", "فروشگاه روی پلتفرم آماده، تا ۲۰ محصول با اطلاعات ارائه‌شده توسط شما و اتصال استاندارد یک سرویس پرداخت. دو دور اصلاح؛ فروشگاه اختصاصی شامل نمی‌شود.", "یک دستیار محدود پرسش‌وپاسخ یا یک گردش‌کار خودکار ساده. امکان اجرا و سقف استفاده پیش از شروع توافق می‌شود؛ دو دور اصلاح.", "یک ساعت بررسی نیازها و پیشنهاد قدم‌های عملی بعدی."],
    unit: "برای هر ساعت", guide: "مبلغ دلاری صرفاً راهنمای تقریبی با فرض هر دلار حدود ۱۰ کرون است و نرخ زنده ارز نیست. ارز پایه کرون سوئد است. قیمت خدمات کسب‌وکار پیش از مالیات قابل‌اعمال نمایش داده می‌شود؛ مالیات و مبلغ کامل پرداخت در پیشنهاد قیمت روشن خواهد بود.", cta: "درخواست برآورد شفاف", terms: "شفافیت، پیش از تصمیم شما", rules: [
      ["پیش از قرارداد", "پیشنهاد قیمت کتبی برای محدوده و مبلغ مشخص، ۱۴ روز اعتبار دارد. اگر تغییر محدوده بخواهید، نیاز فنی تازه‌ای مشخص شود یا اعتبار پیشنهاد پایان یابد، دلیل هر تغییر توضیح داده می‌شود و پیشنهاد جدید پیش از توافق برای تأیید شما ارائه خواهد شد."],
      ["پس از توافق", "مبلغ برای محدوده توافق‌شده ثابت می‌ماند؛ حتی اگر نرخ ارز تغییر کند. کار اضافه تنها پس از تأیید کتبی قیمت و زمان‌بندی آن توسط شما شروع می‌شود. خروجی‌ها، دورهای اصلاح، ارز پرداخت و مراحل پرداخت در قرارداد مشخص می‌شوند."],
      ["هزینه‌ها از ابتدا روشن‌اند", "دامنه، میزبانی، اشتراک پلتفرم، مصرف هوش مصنوعی و API، منابع دارای مجوز و ترجمه جداگانه‌اند مگر صریحاً در بسته گنجانده شوند. هزینه‌های دوره‌ای و کارمزد سرویس پرداخت پیش از توافق مشخص می‌شوند. هزینه تازه‌ای از طرف ELORNA بدون تأیید شما اضافه نمی‌شود."],
      ["فرصتی برای شروع کوچک‌تر", "اگر بودجه محدود دارید، با توجه به محدوده و ظرفیت کاری می‌توانیم مرحله اول کوچک‌تر یا پرداخت بر اساس تحویل مرحله‌ای را بررسی کنیم. انجمن‌ها و پروژه‌های اجتماعی نیز می‌توانند درخواست برنامه متناسب بدهند. برای خرید خدمات بیش از نیازتان تحت فشار قرار نمی‌گیرید."]],
    portfolio: "استودیوی مفهومی", portfolioTitle: "پنج مسیر طراحی، با توجه به جزئیات", disclosure: "این طراحی‌های فرضی برای نمایش رویکردهای ممکن ساخته شده‌اند؛ سفارش مشتری یا محصول عملیاتی نیستند و نتیجه‌ای برای مشتری ادعا نمی‌کنند.", badge: "نمونه مفهومی فرضی", preview: "طرح نمایشی ثابت", descriptions: ["طرح فروشگاه گل با دسته‌بندی مناسبت‌ها، کارت‌های خوانای محصول و مسیر سنجیده سفارش.", "طرح استودیوی زیبایی با معرفی روشن خدمات، قیمت‌ها و مسیر دلپذیر رزرو.", "طرح رستوران ایرانی‌ـ‌اسکاندیناوی با منوی سه‌زبانه و مسیر روشن رزرو میز.", "طرح انجمن اجتماعی با اطلاعات خوانا و مسیر خوشایند مشارکت داوطلبان.", "طرح داشبورد بنیان‌گذار برای وظایف، درخواست‌ها و پاسخ‌های کمک‌گرفته از AI با بازبینی انسان."],
    mock: ["گل‌هایی برای لحظه‌های زندگی", "زمانی کوچک، برای خودت", "کنار میز ما جمع شوید", "قدم‌های کوچک، امکان‌های مشترک", "قدم بعدی‌ات را روشن ببین"],
    feedbackTitle: "اعتماد با بازخورد صادقانه رشد می‌کند", feedbackText: "ELORNA در حال ساخت مجموعه پروژه‌های مشتریان است. پس از تکمیل پروژه‌ها، بازخوردهای تأییدشده با اجازه مشتری منتشر خواهند شد. فعلاً می‌توانید نمونه‌های مفهومی مشخص‌شده را بررسی کنید و برای شناخت روش کار، پیشنهاد کتبی درخواست دهید.", feedbackCta: "تجربه‌تان را به اشتراک بگذارید", feedbackFoot: "با ELORNA کار کرده‌اید؟ بگویید چه چیزی کمک کرد و چه چیزی می‌تواند بهتر شود. انتشار نظر نیازمند اجازه شماست و مثبت‌بودن بازخورد شرط نیست.",
  },
};
export default function OfferSections({ language }: { language: Language }) {
  const t = content[language];
  const format = (n: number) => n.toLocaleString(language === "fa" ? "fa-IR" : language === "sv" ? "sv-SE" : "en-US");
  return <div className="offers" lang={language} dir={language === "fa" ? "rtl" : "ltr"}>
    <section className="offers-section" id="pricing" aria-labelledby="pricing-title">
      <p className="offers-label">{t.label}</p><h2 id="pricing-title">{t.title}</h2><p className="offers-intro">{t.intro}</p>
      <div className="offers-grid">{names.map((name, i) => <article className="offers-card" key={name}>
        <span className="offers-number" aria-hidden="true">0{i + 1}</span><h3>{name}</h3>
        <p className="offers-price"><bdi>{format(prices[i][0])}{i < 5 ? `–${format(prices[i][1])}` : ""} SEK</bdi></p>
        <p className="offers-usd"><bdi>≈ ${format(prices[i][0] / 10)}{i < 5 ? `–${format(prices[i][1] / 10)}` : ""} USD</bdi>{i === 5 ? ` · ${t.unit}` : ""}</p>
        <p>{t.scopes[i]}</p><a className="offers-link" href="#contact">{t.cta} <span aria-hidden="true">↗</span></a>
      </article>)}</div>
      <p className="offers-note">{t.guide}</p>
      <div className="offers-terms"><h3>{t.terms}</h3>{t.rules.map(([title, text]) => <details key={title}><summary>{title}</summary><p>{text}</p></details>)}</div>
    </section>
    <section className="offers-section" id="concepts" aria-labelledby="concepts-title">
      <p className="offers-label">{t.portfolio}</p><h2 id="concepts-title">{t.portfolioTitle}</h2><p className="offers-intro">{t.disclosure}</p>
      <div className="concept-grid">{concepts.map((name, i) => <article className={`concept-card concept-${i}`} key={name}>
        <figure className="concept-preview"><div className="concept-browser" aria-hidden="true"><span>● ● ●</span><span>{name}</span></div><div className="concept-canvas" aria-hidden="true"><span className="concept-wordmark">{name}</span><strong>{t.mock[i]}</strong><div className="concept-art">{i === 0 ? "✿" : i === 1 ? "✧" : i === 2 ? "☼" : i === 3 ? "♡" : "◎"}</div><div className="concept-blocks"><span/><span/><span/></div></div><figcaption>{t.preview}</figcaption></figure>
        <div className="concept-copy"><span className="offers-label">{t.badge}</span><h3>{name}</h3><p>{t.descriptions[i]}</p></div>
      </article>)}</div>
    </section>
    <section className="offers-section offers-feedback" id="feedback" aria-labelledby="feedback-title"><h2 id="feedback-title">{t.feedbackTitle}</h2><p className="offers-intro">{t.feedbackText}</p><a className="offers-button" href={`mailto:contact@elorna.net?subject=${encodeURIComponent("ELORNA — " + t.feedbackCta)}`}>{t.feedbackCta}</a><p className="offers-note">{t.feedbackFoot}</p></section>
  </div>;
}
