const posts=[
{tag:"AI • STRATEGY",title:"Where AI should help — and where founders should stay in control.",excerpt:"Use AI to remove repetitive work, surface options and speed up research — while keeping positioning, risk and final decisions human.",read:"4 MIN"},
{tag:"BUILD",title:"From idea to a launch-ready business foundation.",excerpt:"A strong launch starts with a clear offer, a specific audience and a small set of assumptions you can actually test.",read:"5 MIN"},
{tag:"SELL",title:"A customer journey should feel obvious.",excerpt:"Reduce friction between interest and action by making the next step visible, useful and measurable at every touchpoint.",read:"4 MIN"},
{tag:"GROW",title:"Growth is not more activity. It is better feedback.",excerpt:"Turn signals into focused experiments instead of spreading time and budget across every possible channel.",read:"5 MIN"},
{tag:"SYSTEMS",title:"Why connected workflows beat another stack of tools.",excerpt:"The goal is not more software. It is less context switching, cleaner information and a clearer operating rhythm.",read:"6 MIN"},
{tag:"FOUNDER NOTES",title:"Clarity is a competitive advantage.",excerpt:"When priorities are visible, teams move faster, customers understand the offer sooner and AI becomes far more useful.",read:"3 MIN"}
];
export default function Blog(){return <main className="productPage"><nav className="productNav"><a href="/">← ELORNA</a><span>BLOG • INSIGHTS</span></nav><div className="productWrap"><span className="moduleTag">ELORNA JOURNAL</span><h1>Ideas worth<br/>building on.</h1><p className="productLead">Original ELORNA notes on AI, business systems, brand, sales and sustainable growth. Clear thinking, no invented case studies and no hype.</p><div className="blogGrid">{posts.map(p=><article className="blogCard" key={p.title}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><span className="blogMeta">{p.tag}</span><span className="blogMeta">{p.read}</span></div><h2>{p.title}</h2><p>{p.excerpt}</p><span className="moduleTag">ELORNA EDITORIAL</span></article>)}</div></div></main>}
