const stages = [
  ["BUILD", "Turn an idea into a focused business — strategy, positioning, brand direction and a launch-ready plan.", "Pricing based on project scope • clear estimate before work begins"],
  ["SELL", "Create a clearer route from offer to customer with a structured sales journey and measurable conversion points.", "Pricing based on project scope • clear estimate before work begins"],
  ["GROW", "Use business data and AI-assisted analysis to identify bottlenecks, priorities and measurable next steps.", "Pricing based on project scope • clear estimate before work begins"],
  ["CAPITAL", "Organize business fundamentals and readiness information for future capital conversations — without promises of funding.", "Pricing based on project scope • clear estimate before work begins"],
];

const showcase = [
  ["THE CHALLENGE", "Too many tools. Too much complexity.", "Entrepreneurs lose time moving between disconnected tools, services and decisions. ELORNA brings the journey together.", "/problem.jpg"],
  ["THE SOLUTION", "One intelligent business ecosystem.", "Strategy, brand, sales, growth and AI — connected through one clear operating path.", "/our-solution.jpg"],
  ["BUILD", "From idea to launch.", "Clarify the offer, positioning and brand direction, then turn them into a practical launch-ready foundation.", "/build.jpg"],
  ["SELL", "Turn attention into revenue.", "Map the customer journey, define conversion touchpoints and measure what happens next.", "/sell.jpg"],
  ["GROW", "Make growth measurable.", "Review performance data, identify bottlenecks and turn AI-assisted insights into focused tests.", "/grow.jpg"],
  ["CAPITAL", "Prepare for the next level.", "Structure business fundamentals and growth evidence for future funding conversations. No funding outcome is promised.", "/invest.jpg"],
  ["INTELLIGENCE LAYER", "AI that works with your business.", "Use intelligent assistance to reduce repetitive work while keeping important decisions under human control.", "/Ai-power.jpg"],
  ["THE VISION", "Build today. Shape tomorrow.", "Intelligent infrastructure for ambitious founders who want to build beyond borders.", "/future.jpg"],
];

const css = `
:root{--bg:#02070d;--panel:#07131f;--gold:#d6a34a;--text:#f7f3eb;--muted:#c7d0d9;--line:rgba(214,163,74,.28)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg)}
.elorna{min-height:100vh;color:var(--text);font-family:Manrope,"Avenir Next",Arial,sans-serif;background:radial-gradient(circle at 50% -10%,#15314a 0,#07131f 26%,#02070d 66%);overflow:hidden}
.nav{position:sticky;top:0;z-index:50;min-height:78px;padding:0 5%;display:flex;align-items:center;justify-content:space-between;gap:24px;border-bottom:1px solid var(--line);background:rgba(2,7,13,.94)}
.brand{display:flex;align-items:center;gap:12px;color:#e8bd70;text-decoration:none;letter-spacing:6px;font:600 23px Georgia,serif}.brand img{width:42px;height:42px;border-radius:50%;object-fit:cover}.navlinks{display:flex;gap:28px}.navlinks a,.secondary{color:#dce3e9;text-decoration:none;font-size:13px;letter-spacing:1px}.navlinks a:hover,.secondary:hover{color:#f0c87e}.actions{display:flex;align-items:center;gap:14px}.lang{color:#e8bd70;text-decoration:none;font-size:12px}.primary{display:inline-flex;align-items:center;justify-content:center;gap:10px;padding:14px 22px;border:1px solid #f1c46d;border-radius:999px;background:linear-gradient(135deg,#f0c66f,#bd7a28);color:#071019;text-decoration:none;font-weight:800;letter-spacing:.4px;box-shadow:0 10px 36px rgba(214,163,74,.24);transition:.35s ease}.primary:hover{transform:translateY(-3px) scale(1.015);box-shadow:0 16px 46px rgba(214,163,74,.38)}
.hero{min-height:82vh;padding:80px 7%;display:grid;grid-template-columns:1.05fr .95fr;align-items:center;gap:7vw}.heroCopy{animation:rise .9s ease both}.kicker{color:#efc46e;font-size:11px;letter-spacing:3px;font-weight:800}.hero h1{font:500 clamp(48px,6.5vw,92px)/.98 Georgia,serif;letter-spacing:-2px;margin:20px 0}.gold{color:#e7bd6c}.lead{max-width:720px;color:#d2d9e0;font-size:17px;line-height:1.8}.visual{position:relative;animation:float 7s ease-in-out infinite}.visual:before{content:"";position:absolute;inset:-10%;background:radial-gradient(circle,rgba(214,163,74,.18),transparent 65%)}.visual img{position:relative;width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:34px;border:1px solid var(--line);box-shadow:0 40px 90px rgba(0,0,0,.45);transition:transform .7s ease}.visual:hover img{transform:scale(1.025) rotate(.4deg)}
.section{padding:90px 7%;border-top:1px solid rgba(214,163,74,.16)}.section h2{font:500 clamp(36px,5vw,68px)/1.05 Georgia,serif;margin:14px 0 20px}.center{text-align:center;max-width:980px;margin:auto}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:44px}.card{background:linear-gradient(145deg,#0d2234,#071522);border:1px solid var(--line);border-radius:24px;padding:28px;transition:.4s ease;box-shadow:0 18px 50px rgba(0,0,0,.2)}.card:hover{transform:translateY(-8px);border-color:rgba(224,178,94,.6);box-shadow:0 24px 65px rgba(0,0,0,.34)}.card h3{color:#edc476;letter-spacing:2px}.card p{color:#d0d7de;line-height:1.7}.price{display:block;margin-top:18px;padding-top:16px;border-top:1px solid var(--line);color:#f0d39d;font-size:12px;line-height:1.5}
.show{display:grid;grid-template-columns:1fr 1fr;gap:7vw;align-items:center;padding:70px 7%;border-top:1px solid rgba(214,163,74,.14)}.show:nth-child(even) .pic{order:2}.pic{overflow:hidden;border-radius:28px;border:1px solid var(--line);box-shadow:0 28px 70px rgba(0,0,0,.35)}.pic img{width:100%;display:block;aspect-ratio:16/10;object-fit:contain;background:#071522;transition:transform .8s ease}.pic:hover img{transform:scale(1.025)}.show h2{font:500 clamp(34px,4vw,58px)/1.05 Georgia,serif;margin:12px 0}.show p{color:#d0d7de;line-height:1.8}
.proof{display:grid;grid-template-columns:.9fr 1.1fr;gap:50px;align-items:start;background:linear-gradient(180deg,#06111d,#0a1d2e)}.proofFlow{display:grid;gap:12px}.proofStep{padding:18px 20px;border:1px solid rgba(230,188,112,.4);border-radius:18px;background:#0d263a;color:#f4f0e8;transition:.3s}.proofStep:hover{transform:translateX(8px);border-color:#e6bc70}.notice{margin-top:24px;color:#b7c2cc;font-size:13px;line-height:1.7}.founder{display:grid;grid-template-columns:.8fr 1.2fr;gap:40px;background:#071827}.founderCard strong{display:block;font:500 34px Georgia,serif;color:#f2cc82;margin-bottom:14px}.founderCard a{color:#f0c56f}
.cta{text-align:center;padding:92px 7%;background:linear-gradient(180deg,#0b2235 0%,#102b40 50%,#071827 100%);border-top:1px solid rgba(231,189,108,.35);border-bottom:1px solid rgba(231,189,108,.25)}.cta .kicker{color:#f2cd82}.cta h2{font:400 clamp(44px,6vw,78px)/1.04 Georgia,serif;color:#fff;margin:16px 0 22px;text-shadow:0 3px 20px rgba(0,0,0,.25)}.cta .lead{color:#e2e8ed;font-size:18px}
.contact{display:grid;grid-template-columns:.8fr 1.2fr;gap:45px;background:linear-gradient(135deg,#0b2133,#061522);align-items:center}.contact h2{color:#fff}.contact .lead{color:#dce3e8}.form{display:grid;gap:14px;background:#0d2638;border-color:rgba(238,197,118,.42);box-shadow:0 22px 55px rgba(0,0,0,.28)}.form input,.form textarea{width:100%;padding:16px;border-radius:14px;border:1px solid rgba(232,193,116,.35);background:#071827;color:#fff;font:inherit;outline:none}.form input:focus,.form textarea:focus{border-color:#e9bd68;box-shadow:0 0 0 3px rgba(233,189,104,.12)}.form input::placeholder,.form textarea::placeholder{color:#aebbc6}.form textarea{min-height:140px;resize:vertical}.form button{border:0;cursor:pointer}.footer{padding:35px 7%;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:20px;background:#020912;color:#aeb9c3;font-size:12px}.footer a{color:#e4ba68;text-decoration:none}
@keyframes rise{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:none}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
@media(max-width:900px){.navlinks{display:none}.hero,.show,.proof,.founder,.contact{grid-template-columns:1fr}.hero{padding-top:55px}.show:nth-child(even) .pic{order:0}.grid4{grid-template-columns:1fr 1fr}.footer{flex-direction:column}.hero h1{font-size:52px}}
@media(max-width:560px){.nav{padding:0 4%}.brand{font-size:18px;letter-spacing:4px}.nav .primary{display:none}.hero,.section,.show{padding-left:5%;padding-right:5%}.grid4{grid-template-columns:1fr}}
`;

export default function Home(){return <main className="elorna">
<style dangerouslySetInnerHTML={{__html:css}} />
<header className="nav"><a className="brand" href="#top"><img src="/elorna-emblem.jpg" alt="ELORNA gold emblem"/><span>ELORNA</span></a><nav className="navlinks" aria-label="Primary navigation"><a href="#system">System</a><a href="#journey">Journey</a><a href="#proof">Proof</a></nav><div className="actions"><a className="lang" href="/fa" lang="fa">FA فارسی</a><a className="lang" href="/sv" lang="sv">SV</a><a className="primary" href="#contact">Start Building <span>→</span></a></div></header>
<section className="hero" id="top"><div className="heroCopy"><div className="kicker">AI • IT • BUSINESS • FUTURE</div><h1>Build the business.<br/><span className="gold">Shape the future.</span></h1><p className="lead">ELORNA connects strategy, launch, sales and growth in one AI-assisted path — giving founders a clearer next step without forcing them to manage a dozen disconnected tools.</p></div><div className="visual"><img src="/elorna-vision.jpg" alt="ELORNA vision for an AI-assisted connected business ecosystem"/></div></section>
<section className="section center" id="system"><div className="kicker">WHY ELORNA</div><h2>One connected journey.<br/><span className="gold">Founder control at every step.</span></h2><p className="lead">Strategy, execution and growth are brought into one coherent system. AI supports the work; important business decisions remain human-approved.</p></section>
<section className="section" id="journey"><div className="center"><div className="kicker">THE ELORNA JOURNEY</div><h2>Build. Sell. Grow. Prepare.</h2><p className="lead">Pricing is based on project scope. A clear scope and estimate are provided before paid work begins.</p></div><div className="grid4">{stages.map(([title,text,price])=><article className="card" key={title}><h3>{title}</h3><p>{text}</p><span className="price">{price}</span></article>)}</div></section>
<section>{showcase.map(([eyebrow,title,text,image])=><article className="show" key={title}><div className="pic"><img src={image} alt={`${title} — ELORNA ${eyebrow.toLowerCase()} concept`}/></div><div><div className="kicker">{eyebrow}</div><h2>{title}</h2><p>{text}</p></div></article>)}</section>
<section className="section proof" id="proof"><div><div className="kicker">REAL BUILD EVIDENCE</div><h2>ELORNA is the first<br/><span className="gold">live case study.</span></h2><p className="lead">Instead of inventing testimonials, ELORNA shows a real product being built in public: its own connected brand and web experience. The current live build includes a three-language website, a working contact journey, responsive presentation and a consistent brand system.</p><p className="notice">This is first-party build evidence, not a client testimonial or a claim of guaranteed results. Verified pilot feedback and permission-based client evidence will be added here when available.</p></div><div className="proofFlow">{["LIVE — ELORNA multilingual website (EN / SV / FA)","LIVE — Working contact and inquiry journey","LIVE — Responsive desktop and mobile experience","LIVE — Connected visual brand system","NEXT — Verified pilot feedback with permission"].map(x=><div className="proofStep" key={x}>{x}</div>)}</div></section>
<section className="section founder"><div><div className="kicker">FOUNDER-LED</div><h2>Accountability has a name.</h2></div><div className="card founderCard"><strong>Elnaz Ghanbari</strong><p>Founder of ELORNA, leading product direction, brand system and founder experience. ELORNA is being built around a practical principle: AI should reduce complexity, explain the next step and keep important decisions under human control.</p><a href="mailto:elnaz@elorna.net">elnaz@elorna.net</a></div></section>
<section className="cta"><div className="kicker">THE NEXT CHAPTER STARTS HERE</div><h2>Ready to build<br/><span className="gold">with more clarity?</span></h2><p className="lead" style={{margin:"0 auto"}}>A focused first conversation clarifies fit, scope and the next practical step.</p></section>
<section className="section contact" id="contact"><div><div className="kicker">CONTACT ELORNA</div><h2>Start a serious conversation.</h2><p className="lead">Pricing is based on project scope. Tell us about your project and ELORNA will provide a clear estimate before work begins.</p><p><a className="secondary" href="mailto:contact@elorna.net">contact@elorna.net</a></p></div><form className="card form" action="https://formsubmit.co/contact@elorna.net" method="POST"><input type="hidden" name="_subject" value="New ELORNA website inquiry"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_next" value="https://elorna.net/thank-you"/><input name="name" required placeholder="Your name" aria-label="Your name"/><input name="email" type="email" required placeholder="Email" aria-label="Email"/><textarea name="message" required placeholder="What are you building and where do you need help?" aria-label="Message"/><button className="primary" type="submit">Send to ELORNA →</button></form></section>
<footer className="footer"><span>© 2026 ELORNA • AI-assisted • Human-approved</span><span><a href="mailto:support@elorna.net">support@elorna.net</a> · <a href="https://www.linkedin.com/company/elorna">LinkedIn</a> · <a href="https://www.instagram.com/elorna.official">Instagram</a></span></footer>
</main>}