const stages = [
  ["BUILD", "Turn an idea into a focused business — strategy, positioning, brand direction and a launch-ready plan.", "Pricing based on project scope • clear estimate before work begins"],
  ["SELL", "Create a clearer route from offer to customer with a structured sales journey and measurable conversion points.", "Pricing based on project scope • clear estimate before work begins"],
  ["GROW", "Use business data and AI-assisted analysis to identify bottlenecks, priorities and measurable next steps.", "Pricing based on project scope • clear estimate before work begins"],
  ["CAPITAL", "Organize business fundamentals and readiness information for future capital conversations — without promises of funding.", "Pricing based on project scope • clear estimate before work begins"],
];

const showcase = [
  ["THE CHALLENGE", "Too many tools. Too much complexity.", "Entrepreneurs lose time moving between disconnected tools, services and decisions. ELORNA brings the journey together.", "/problem.jpg"],
  ["THE SOLUTION", "One intelligent business ecosystem.", "Strategy, brand, sales, growth and AI — connected through one clear operating path.", "/our-solution.jpg"],
  ["BUILD", "From idea to launch.", "Clarify the offer, positioning and brand direction, then turn them into a practical launch-ready foundation.", "/build.jpg"],
  ["SELL", "Turn attention into revenue.", "Map the customer journey, define conversion touchpoints and measure what happens next.", "/sell.jpg"],
  ["GROW", "Make growth measurable.", "Review performance data, identify bottlenecks and turn AI-assisted insights into focused tests.", "/grow.jpg"],
  ["CAPITAL", "Prepare for the next level.", "Structure business fundamentals and growth evidence for future funding conversations. No funding outcome is promised.", "/invest.jpg"],
  ["INTELLIGENCE LAYER", "AI that works with your business.", "Use intelligent assistance to reduce repetitive work while keeping important decisions under human control.", "/Ai-power.jpg"],
  ["THE VISION", "Build today. Shape tomorrow.", "Intelligent infrastructure for ambitious founders who want to build beyond borders.", "/future.jpg"],
];

const css = `
:root{--bg:#02070d;--panel:#07131f;--gold:#d6a34a;--text:#f7f3eb;--muted:#aeb8c3;--line:rgba(214,163,74,.22)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg)}
.elorna{min-height:100vh;color:var(--text);font-family:Manrope,"Avenir Next",Arial,sans-serif;background:radial-gradient(circle at 50% -10%,#15314a 0,#07131f 26%,#02070d 66%);overflow:hidden}
.nav{position:sticky;top:0;z-index:50;min-height:78px;padding:0 5%;display:flex;align-items:center;justify-content:space-between;gap:24px;border-bottom:1px solid var(--line);background:rgba(2,7,13,.86);backdrop-filter:blur(18px)}
.brand{display:flex;align-items:center;gap:12px;color:#e8bd70;text-decoration:none;letter-spacing:6px;font:600 23px Georgia,serif}.brand img{width:42px;height:42px;border-radius:50%;object-fit:cover}.navlinks{display:flex;gap:28px}.navlinks a,.secondary{color:#c9d0d7;text-decoration:none;font-size:13px;letter-spacing:1px}.navlinks a:hover,.secondary:hover{color:#f0c87e}.actions{display:flex;align-items:center;gap:14px}.lang{color:#e8bd70;text-decoration:none;font-size:12px}.primary{display:inline-flex;align-items:center;justify-content:center;gap:10px;padding:14px 22px;border:1px solid #e0b25e;border-radius:999px;background:linear-gradient(135deg,#e3b75f,#a96d20);color:#071019;text-decoration:none;font-weight:800;letter-spacing:.4px;box-shadow:0 10px 36px rgba(214,163,74,.18);transition:.35s ease}.primary:hover{transform:translateY(-3px) scale(1.015);box-shadow:0 16px 46px rgba(214,163,74,.32)}
.hero{min-height:82vh;padding:80px 7%;display:grid;grid-template-columns:1.05fr .95fr;align-items:center;gap:7vw}.heroCopy{animation:rise .9s ease both}.kicker{color:#d8ad61;font-size:11px;letter-spacing:3px;font-weight:800}.hero h1{font:500 clamp(48px,6.5vw,92px)/.98 Georgia,serif;letter-spacing:-2px;margin:20px 0}.gold{color:#dcb463}.lead{max-width:720px;color:#bdc6cf;font-size:17px;line-height:1.8}.heroCta{display:flex;align-items:center;gap:20px;margin-top:30px}.visual{position:relative;animation:float 7s ease-in-out infinite}.visual:before{content:"";position:absolute;inset:-10%;background:radial-gradient(circle,rgba(214,163,74,.18),transparent 65%);filter:blur(20px)}.visual img{position:relative;width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:34px;border:1px solid var(--line);box-shadow:0 40px 90px rgba(0,0,0,.45);transition:transform .7s ease,filter .7s ease}.visual:hover img{transform:scale(1.025) rotate(.4deg);filter:brightness(1.08)}
.section{padding:90px 7%;border-top:1px solid rgba(214,163,74,.12)}.section h2{font:500 clamp(36px,5vw,68px)/1.05 Georgia,serif;margin:14px 0 20px}.center{text-align:center;max-width:980px;margin:auto}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:44px}.card{background:linear-gradient(145deg,rgba(12,29,44,.88),rgba(4,12,20,.9));border:1px solid var(--line);border-radius:24px;padding:28px;transition:.4s ease;box-shadow:0 18px 50px rgba(0,0,0,.2)}.card:hover{transform:translateY(-8px);border-color:rgba(224,178,94,.55);box-shadow:0 24px 65px rgba(0,0,0,.34)}.card h3{color:#e6bc70;letter-spacing:2px}.card p{color:#b9c3cc;line-height:1.7}.price{display:block;margin-top:18px;padding-top:16px;border-top:1px solid var(--line);color:#e7c98f;font-size:12px;line-height:1.5}
.show{display:grid;grid-template-columns:1fr 1fr;gap:7vw;align-items:center;padding:70px 7%;border-top:1px solid rgba(214,163,74,.1)}.show:nth-child(even) .pic{order:2}.pic{overflow:hidden;border-radius:28px;border:1px solid var(--line);box-shadow:0 28px 70px rgba(0,0,0,.35)}.pic img{width:100%;display:block;aspect-ratio:16/10;object-fit:cover;transition:transform 1s cubic-bezier(.2,.8,.2,1),filter .7s}.pic:hover img{transform:scale(1.07);filter:contrast(1.05) brightness(1.06)}.show h2{font:500 clamp(34px,4vw,58px)/1.05 Georgia,serif;margin:12px 0}.show p{color:#b9c3cc;line-height:1.8}
.proof{display:grid;grid-template-columns:.9fr 1.1fr;gap:50px;align-items:start}.proofFlow{display:grid;gap:12px}.proofStep{padding:18px 20px;border:1px solid var(--line);border-radius:18px;background:rgba(8,22,34,.75);transition:.3s}.proofStep:hover{transform:translateX(8px);border-color:#d6a34a}.notice{margin-top:24px;color:#95a4b2;font-size:13px;line-height:1.7}.founder{display:grid;grid-template-columns:.8fr 1.2fr;gap:40px}.founderCard strong{display:block;font:500 34px Georgia,serif;color:#efc97e;margin-bottom:14px}.founderCard a{color:#e0b25e}.cta{text-align:center;padding:110px 7%;background:radial-gradient(circle at 50% 50%,rgba(38,77,105,.35),transparent 60%)}.cta h2{font:500 clamp(44px,6vw,78px)/1 Georgia,serif}.contact{display:grid;grid-template-columns:.8fr 1.2fr;gap:45px}.form{display:grid;gap:14px}.form input,.form textarea{width:100%;padding:15px 16px;border-radius:14px;border:1px solid var(--line);background:#04101a;color:white;font:inherit}.form textarea{min-height:140px;resize:vertical}.form button{border:0;cursor:pointer}.footer{padding:35px 7%;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:20px;color:#82909c;font-size:12px}.footer a{color:#d8ad61;text-decoration:none}
@keyframes rise{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:none}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
@media(max-width:900px){.navlinks{display:none}.hero,.show,.proof,.founder,.contact{grid-template-columns:1fr}.hero{padding-top:55px}.show:nth-child(even) .pic{order:0}.grid4{grid-template-columns:1fr 1fr}.footer{flex-direction:column}.hero h1{font-size:52px}}
@media(max-width:560px){.nav{padding:0 4%}.brand{font-size:18px;letter-spacing:4px}.nav .primary{display:none}.hero,.section,.show{padding-left:5%;padding-right:5%}.grid4{grid-template-columns:1fr}.heroCta{align-items:flex-start;flex-direction:column}}
`;

export default function Home(){return <main className="elorna">
<style dangerouslySetInnerHTML={{__html:css}} />
<header className="nav"><a className="brand" href="#top"><img src="/elorna-emblem.jpg" alt="ELORNA gold emblem"/><span>ELORNA</span></a><nav className="navlinks" aria-label="Primary navigation"><a href="#system">System</a><a href="#journey">Journey</a><a href="#proof">Proof</a><a href="#contact">Contact</a></nav><div className="actions"><a className="lang" href="/fa" lang="fa">FA فارسی</a><a className="lang" href="/sv" lang="sv">SV</a><a className="primary" href="#contact">Start Building <span>→</span></a></div></header>
<section className="hero" id="top"><div className="heroCopy"><div className="kicker">AI • IT • BUSINESS • FUTURE</div><h1>Build the business.<br/><span className="gold">Shape the future.</span></h1><p className="lead">ELORNA connects strategy, launch, sales and growth in one AI-assisted path — giving founders a clearer next step without forcing them to manage a dozen disconnected tools.</p><div className="heroCta"><a className="primary" href="#contact">Start Building <span>→</span></a><a className="secondary" href="#journey">How it works ↓</a></div></div><div className="visual"><img src="/elorna-vision.jpg" alt="ELORNA vision for an AI-assisted connected business ecosystem"/></div></section>
<section className="section center" id="system"><div className="kicker">WHY ELORNA</div><h2>One connected journey.<br/><span className="gold">Founder control at every step.</span></h2><p className="lead">Strategy, execution and growth are brought into one coherent system. AI supports the work; important business decisions remain human-approved.</p></section>
<section className="section" id="journey"><div className="center"><div className="kicker">THE ELORNA JOURNEY</div><h2>Build. Sell. Grow. Prepare.</h2><p className="lead">Pricing is based on project scope. A clear scope and estimate are provided before paid work begins.</p></div><div className="grid4">{stages.map(([title,text,price])=><article className="card" key={title}><h3>{title}</h3><p>{text}</p><span className="price">{price}</span></article>)}</div></section>
<section>{showcase.map(([eyebrow,title,text,image])=><article className="show" key={title}><div className="pic"><img src={image} alt={`${title} — ELORNA ${eyebrow.toLowerCase()} concept`}/></div><div><div className="kicker">{eyebrow}</div><h2>{title}</h2><p>{text}</p></div></article>)}</section>
<section className="section proof" id="proof"><div><div className="kicker">TRANSPARENT PROOF</div><h2>Show the work.<br/><span className="gold">Never invent the result.</span></h2><p className="lead">ELORNA is early-stage. Until verified client outcomes are available, the site shows its method transparently instead of publishing fabricated testimonials or guaranteed results.</p><p className="notice">As real pilot work and permission-based feedback become available, this section is designed to be replaced with verified evidence.</p></div><div className="proofFlow">{["01 — Idea & business context","02 — Positioning & offer","03 — Launch plan","04 — Sales journey","05 — Measure & improve"].map(x=><div className="proofStep" key={x}>{x}</div>)}</div></section>
<section className="section founder"><div><div className="kicker">FOUNDER-LED</div><h2>Accountability has a name.</h2></div><div className="card founderCard"><strong>Elnaz Ghanbari</strong><p>Founder of ELORNA, leading product direction, brand system and founder experience. ELORNA is being built around a practical principle: AI should reduce complexity, explain the next step and keep important decisions under human control.</p><a href="mailto:elnaz@elorna.net">elnaz@elorna.net</a></div></section>
<section className="cta"><div className="kicker">THE NEXT CHAPTER STARTS HERE</div><h2>Ready to build<br/><span className="gold">with more clarity?</span></h2><p className="lead" style={{margin:"0 auto 30px"}}>Tell ELORNA what you are building. The first conversation clarifies fit, scope and the next practical step.</p><a className="primary" href="#contact">Start Building <span>→</span></a></section>
<section className="section contact" id="contact"><div><div className="kicker">CONTACT ELORNA</div><h2>Start a serious conversation.</h2><p className="lead">Pricing is based on project scope. Tell us about your project and ELORNA will provide a clear estimate before work begins.</p><p><a className="secondary" href="mailto:contact@elorna.net">contact@elorna.net</a></p></div><form className="card form" action="https://formsubmit.co/contact@elorna.net" method="POST"><input type="hidden" name="_subject" value="New ELORNA website inquiry"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_next" value="https://elorna.net/thank-you"/><input name="name" required placeholder="Your name" aria-label="Your name"/><input name="email" type="email" required placeholder="Email" aria-label="Email"/><textarea name="message" required placeholder="What are you building and where do you need help?" aria-label="Message"/><button className="primary" type="submit">Send to ELORNA →</button></form></section>
<footer className="footer"><span>© 2026 ELORNA • AI-assisted • Human-approved</span><span><a href="mailto:support@elorna.net">support@elorna.net</a> · <a href="https://www.linkedin.com/company/elorna">LinkedIn</a> · <a href="https://www.instagram.com/elorna.official">Instagram</a></span></footer>
</main>}