const stages = [
  ["ساخت", "ایده را به یک کسب‌وکار متمرکز تبدیل کنید؛ از استراتژی و جایگاه‌سازی تا هویت برند و برنامه‌ی آماده برای راه‌اندازی.", "قیمت بر اساس پروژه • برآورد پس از یک مشاوره کوتاه"],
  ["فروش", "مسیر روشن‌تری از پیشنهاد تا مشتری بسازید؛ با سفر مشتری ساختاریافته و نقاط تبدیل قابل‌اندازه‌گیری.", "قیمت بر اساس پروژه • برآورد پس از یک مشاوره کوتاه"],
  ["رشد", "با داده‌های کسب‌وکار و تحلیل کمک‌گرفته از هوش مصنوعی، گلوگاه‌ها و اولویت‌های رشد را پیدا کنید.", "دامنه کار و برآورد هزینه پیش از شروع مشخص می‌شود"],
  ["آمادگی سرمایه", "اطلاعات و پایه‌های کسب‌وکار را برای گفت‌وگوهای آینده درباره سرمایه آماده کنید؛ بدون وعده تأمین سرمایه.", "دامنه اختصاصی • برآورد کتبی پس از بررسی اولیه"],
];

const showcase = [
  ["چالش", "ابزارهای زیاد، پیچیدگی زیاد.", "کارآفرینان زمان زیادی را میان ابزارها، خدمات و تصمیم‌های جدا از هم از دست می‌دهند. ELORNA این مسیر را یکپارچه می‌کند.", "/problem.jpg"],
  ["راه‌حل", "یک اکوسیستم هوشمند کسب‌وکار.", "استراتژی، برند، فروش، رشد و هوش مصنوعی در یک مسیر روشن و متصل کنار هم قرار می‌گیرند.", "/our-solution.jpg"],
  ["ساخت", "از ایده تا راه‌اندازی.", "پیشنهاد، جایگاه و مسیر برند را شفاف کنید و آن‌ها را به یک پایه عملی برای راه‌اندازی تبدیل کنید.", "/build.jpg"],
  ["فروش", "توجه را به درآمد تبدیل کنید.", "سفر مشتری را طراحی کنید، نقاط تبدیل را مشخص کنید و آنچه بعد اتفاق می‌افتد اندازه‌گیری کنید.", "/sell.jpg"],
  ["رشد", "رشد را قابل‌اندازه‌گیری کنید.", "داده‌های عملکرد را بررسی کنید و بینش‌های هوش مصنوعی را به آزمایش‌ها و اولویت‌های مشخص تبدیل کنید.", "/grow.jpg"],
  ["آمادگی سرمایه", "برای مرحله بعد آماده شوید.", "ساختار و شواهد رشد کسب‌وکار را برای گفت‌وگوهای آینده درباره سرمایه آماده کنید. هیچ نتیجه مالی تضمین نمی‌شود.", "/invest.jpg"],
  ["لایه هوشمند", "هوش مصنوعی در خدمت کسب‌وکار شما.", "کارهای تکراری را کاهش دهید و در عین حال تصمیم‌های مهم را تحت کنترل انسانی نگه دارید.", "/Ai-power.jpg"],
  ["چشم‌انداز", "امروز بسازید، فردا را شکل دهید.", "زیرساخت هوشمند برای بنیان‌گذارانی که می‌خواهند فراتر از مرزها رشد کنند.", "/future.jpg"],
];

const css = `
:root{--bg:#02070d;--gold:#d6a34a;--text:#f7f3eb;--muted:#b7c1cb;--line:rgba(214,163,74,.22)}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg)}
.fa{direction:rtl;text-align:right;min-height:100vh;color:var(--text);font-family:Tahoma,"Noto Sans Arabic",Arial,sans-serif;background:radial-gradient(circle at 50% -10%,#15314a 0,#07131f 26%,#02070d 66%);overflow:hidden}.nav{position:sticky;top:0;z-index:50;min-height:78px;padding:0 5%;display:flex;align-items:center;justify-content:space-between;gap:24px;border-bottom:1px solid var(--line);background:rgba(2,7,13,.86);backdrop-filter:blur(18px)}.brand{display:flex;align-items:center;gap:12px;color:#e8bd70;text-decoration:none;letter-spacing:5px;font:600 23px Georgia,serif;direction:ltr}.brand img{width:42px;height:42px;border-radius:50%;object-fit:cover}.navlinks{display:flex;gap:28px}.navlinks a,.secondary{color:#c9d0d7;text-decoration:none;font-size:13px}.navlinks a:hover,.secondary:hover{color:#f0c87e}.actions{display:flex;align-items:center;gap:14px}.lang{color:#e8bd70;text-decoration:none;font-size:12px}.primary{display:inline-flex;align-items:center;justify-content:center;gap:10px;padding:14px 22px;border:1px solid #e0b25e;border-radius:999px;background:linear-gradient(135deg,#e3b75f,#a96d20);color:#071019;text-decoration:none;font-weight:800;box-shadow:0 10px 36px rgba(214,163,74,.18);transition:.35s}.primary:hover{transform:translateY(-3px) scale(1.015);box-shadow:0 16px 46px rgba(214,163,74,.32)}
.hero{min-height:82vh;padding:80px 7%;display:grid;grid-template-columns:1.05fr .95fr;align-items:center;gap:7vw}.heroCopy{animation:rise .9s ease both}.kicker{color:#d8ad61;font-size:11px;letter-spacing:1px;font-weight:800}.hero h1{font:600 clamp(44px,6vw,82px)/1.2 Tahoma,sans-serif;margin:20px 0}.gold{color:#dcb463}.lead{max-width:720px;color:#bdc6cf;font-size:17px;line-height:2}.heroCta{display:flex;align-items:center;gap:20px;margin-top:30px}.visual{position:relative;animation:float 7s ease-in-out infinite}.visual:before{content:"";position:absolute;inset:-10%;background:radial-gradient(circle,rgba(214,163,74,.18),transparent 65%);filter:blur(20px)}.visual img{position:relative;width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:34px;border:1px solid var(--line);box-shadow:0 40px 90px rgba(0,0,0,.45);transition:.7s}.visual:hover img{transform:scale(1.025) rotate(-.4deg);filter:brightness(1.08)}
.section{padding:90px 7%;border-top:1px solid rgba(214,163,74,.12)}.section h2{font:600 clamp(34px,5vw,62px)/1.35 Tahoma,sans-serif;margin:14px 0 20px}.center{text-align:center;max-width:980px;margin:auto}.center .lead{margin-inline:auto}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:44px}.card{background:linear-gradient(145deg,rgba(12,29,44,.88),rgba(4,12,20,.9));border:1px solid var(--line);border-radius:24px;padding:28px;transition:.4s;box-shadow:0 18px 50px rgba(0,0,0,.2)}.card:hover{transform:translateY(-8px);border-color:rgba(224,178,94,.55);box-shadow:0 24px 65px rgba(0,0,0,.34)}.card h3{color:#e6bc70;font-size:22px}.card p{color:#b9c3cc;line-height:2}.price{display:block;margin-top:18px;padding-top:16px;border-top:1px solid var(--line);color:#e7c98f;font-size:12px;line-height:1.8}
.show{display:grid;grid-template-columns:1fr 1fr;gap:7vw;align-items:center;padding:70px 7%;border-top:1px solid rgba(214,163,74,.1)}.show:nth-child(even) .pic{order:2}.pic{overflow:hidden;border-radius:28px;border:1px solid var(--line);box-shadow:0 28px 70px rgba(0,0,0,.35)}.pic img{width:100%;display:block;aspect-ratio:16/10;object-fit:cover;transition:transform 1s cubic-bezier(.2,.8,.2,1),filter .7s}.pic:hover img{transform:scale(1.07);filter:contrast(1.05) brightness(1.06)}.show h2{font:600 clamp(32px,4vw,54px)/1.4 Tahoma,sans-serif;margin:12px 0}.show p{color:#b9c3cc;line-height:2}.proof{display:grid;grid-template-columns:.9fr 1.1fr;gap:50px;align-items:start}.proofFlow{display:grid;gap:12px}.proofStep{padding:18px 20px;border:1px solid var(--line);border-radius:18px;background:rgba(8,22,34,.75);transition:.3s}.proofStep:hover{transform:translateX(-8px);border-color:#d6a34a}.notice{margin-top:24px;color:#95a4b2;font-size:13px;line-height:2}.founder{display:grid;grid-template-columns:.8fr 1.2fr;gap:40px}.founderCard strong{display:block;font-size:30px;color:#efc97e;margin-bottom:14px}.founderCard a{color:#e0b25e}.cta{text-align:center;padding:110px 7%;background:radial-gradient(circle at 50% 50%,rgba(38,77,105,.35),transparent 60%)}.cta h2{font:600 clamp(40px,6vw,70px)/1.4 Tahoma,sans-serif}.contact{display:grid;grid-template-columns:.8fr 1.2fr;gap:45px}.form{display:grid;gap:14px}.form input,.form textarea{width:100%;padding:15px 16px;border-radius:14px;border:1px solid var(--line);background:#04101a;color:white;font:inherit;text-align:right;direction:rtl}.form textarea{min-height:140px;resize:vertical}.form button{border:0;cursor:pointer}.footer{padding:35px 7%;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:20px;color:#82909c;font-size:12px}.footer a{color:#d8ad61;text-decoration:none}
@keyframes rise{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:none}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}@media(max-width:900px){.navlinks{display:none}.hero,.show,.proof,.founder,.contact{grid-template-columns:1fr}.hero{padding-top:55px}.show:nth-child(even) .pic{order:0}.grid4{grid-template-columns:1fr 1fr}.footer{flex-direction:column}}@media(max-width:560px){.nav{padding:0 4%}.brand{font-size:18px}.nav .primary{display:none}.hero,.section,.show{padding-left:5%;padding-right:5%}.grid4{grid-template-columns:1fr}.heroCta{align-items:flex-start;flex-direction:column}}
`;

export default function PersianHome(){return <main className="fa" dir="rtl" lang="fa"><style dangerouslySetInnerHTML={{__html:css}}/>
<header className="nav"><a className="brand" href="#top"><img src="/elorna-emblem.jpg" alt="نشان طلایی ELORNA"/><span>ELORNA</span></a><nav className="navlinks" aria-label="ناوبری اصلی"><a href="#system">سیستم</a><a href="#journey">مسیر</a><a href="#proof">اعتماد</a><a href="#contact">تماس</a></nav><div className="actions"><a className="lang" href="/" lang="en">EN</a><a className="lang" href="/sv" lang="sv">SV</a><a className="primary" href="#contact">شروع همکاری ←</a></div></header>
<section className="hero" id="top"><div className="heroCopy"><div className="kicker">هوش مصنوعی • فناوری • کسب‌وکار • آینده</div><h1>کسب‌وکارت را بساز.<br/><span className="gold">آینده را شکل بده.</span></h1><p className="lead">ELORNA استراتژی، راه‌اندازی، فروش و رشد را در یک مسیر یکپارچه و کمک‌گرفته از هوش مصنوعی به هم متصل می‌کند؛ تا بنیان‌گذار بداند قدم بعدی چیست و مجبور نباشد میان ده‌ها ابزار پراکنده سرگردان شود.</p><div className="heroCta"><a className="primary" href="#contact">شروع همکاری ←</a><a className="secondary" href="#journey">نحوه کار را ببینید ↓</a></div></div><div className="visual"><img src="/elorna-fa-overview.jpg" alt="چشم‌انداز ELORNA برای اکوسیستم یکپارچه کسب‌وکار با کمک هوش مصنوعی"/></div></section>
<section className="section center" id="system"><div className="kicker">چرا ELORNA؟</div><h2>یک مسیر یکپارچه.<br/><span className="gold">کنترل در دست بنیان‌گذار.</span></h2><p className="lead">استراتژی، اجرا و رشد در یک سیستم منسجم کنار هم قرار می‌گیرند. هوش مصنوعی از کار پشتیبانی می‌کند، اما تصمیم‌های مهم کسب‌وکار با تأیید انسان انجام می‌شوند.</p></section>
<section className="section" id="journey"><div className="center"><div className="kicker">مسیر ELORNA</div><h2>بسازید. بفروشید. رشد کنید. آماده شوید.</h2><p className="lead">به‌جای عبارت‌های مبهم، دامنه کار و برآورد هزینه قبل از شروع همکاری پولی شفاف می‌شود.</p></div><div className="grid4">{stages.map(([title,text,price])=><article className="card" key={title}><h3>{title}</h3><p>{text}</p><span className="price">{price}</span></article>)}</div></section>
<section>{showcase.map(([eyebrow,title,text,image])=><article className="show" key={title}><div className="pic"><img src={image} alt={`${title} — تصویر بخش ${eyebrow} در ELORNA`}/></div><div><div className="kicker">{eyebrow}</div><h2>{title}</h2><p>{text}</p></div></article>)}</section>
<section className="section proof" id="proof"><div><div className="kicker">اعتماد شفاف</div><h2>کار را نشان می‌دهیم؛<br/><span className="gold">نتیجه ساختگی نمی‌سازیم.</span></h2><p className="lead">ELORNA در مرحله آغازین است. تا زمانی که نتایج تأییدشده مشتریان واقعی در دسترس باشد، روش کار را شفاف نشان می‌دهیم و از نظر یا نتیجه جعلی و وعده تضمینی استفاده نمی‌کنیم.</p><p className="notice">با شکل‌گیری همکاری‌های پایلوت واقعی و دریافت اجازه برای انتشار بازخورد، این بخش با شواهد تأییدشده تکمیل خواهد شد.</p></div><div className="proofFlow">{["۰۱ — ایده و شرایط کسب‌وکار","۰۲ — جایگاه و پیشنهاد","۰۳ — برنامه راه‌اندازی","۰۴ — مسیر فروش","۰۵ — اندازه‌گیری و بهبود"].map(x=><div className="proofStep" key={x}>{x}</div>)}</div></section>
<section className="section founder"><div><div className="kicker">بنیان‌گذارمحور</div><h2>پشت ELORNA یک انسان واقعی است.</h2></div><div className="card founderCard"><strong>الناز قنبری — Elnaz Ghanbari</strong><p>بنیان‌گذار ELORNA و مسئول جهت محصول، سیستم برند و تجربه بنیان‌گذار. اصل طراحی ELORNA ساده است: هوش مصنوعی باید پیچیدگی را کمتر کند، قدم بعدی را روشن‌تر سازد و تصمیم‌های مهم را تحت کنترل انسان نگه دارد.</p><a href="mailto:elnaz@elorna.net">elnaz@elorna.net</a></div></section>
<section className="cta"><div className="kicker">فصل بعدی از اینجا شروع می‌شود</div><h2>آماده‌اید با<br/><span className="gold">شفافیت بیشتری بسازید؟</span></h2><p className="lead" style={{margin:"0 auto 30px"}}>برای ELORNA بنویسید چه چیزی می‌سازید. گفت‌وگوی اول برای روشن‌شدن تناسب همکاری، دامنه کار و قدم عملی بعدی است.</p><a className="primary" href="#contact">شروع همکاری ←</a></section>
<section className="section contact" id="contact"><div><div className="kicker">تماس با ELORNA</div><h2>یک گفت‌وگوی جدی را شروع کنید.</h2><p className="lead">قیمت بر اساس دامنه پروژه تعیین می‌شود. برای دریافت برآورد روشن پیش از شروع کار، درخواست مشاوره بفرستید.</p><p><a className="secondary" href="mailto:contact@elorna.net">contact@elorna.net</a></p></div><form className="card form" action="https://formsubmit.co/contact@elorna.net" method="POST"><input type="hidden" name="_subject" value="New ELORNA Persian website inquiry"/><input type="hidden" name="_captcha" value="false"/><input type="hidden" name="_next" value="https://elorna.net/thank-you"/><input name="name" required placeholder="نام شما" aria-label="نام شما"/><input name="email" type="email" required placeholder="ایمیل" aria-label="ایمیل"/><textarea name="message" required placeholder="چه چیزی می‌سازید و در کدام بخش به کمک نیاز دارید؟" aria-label="پیام"/><button className="primary" type="submit">ارسال برای ELORNA ←</button></form></section>
<footer className="footer"><span>© ۲۰۲۶ ELORNA • با کمک هوش مصنوعی • با تأیید انسان</span><span><a href="mailto:support@elorna.net">support@elorna.net</a> · <a href="https://www.linkedin.com/company/elorna">LinkedIn</a> · <a href="https://www.instagram.com/elorna.official">Instagram</a></span></footer>
</main>}
