export type ChatLanguage = "en" | "sv" | "fa";
export type ChatMessage = { role: "user" | "assistant"; content: string };
export const chatPrices = "Essential: 3,500–6,000 SEK; Business: 7,500–14,000 SEK; Multilingual: 12,000–22,000 SEK; Online Store: 18,000–32,000 SEK; AI Starter: 6,500–15,000 SEK; Consultation: 500 SEK/hour. Indicative B2B ranges excluding applicable taxes. Domains, hosting, translations, subscriptions and AI usage are separate unless included. USD is approximate at 10 SEK/USD, not a live rate. Written quotes valid 14 days; accepted scope has fixed fee; changes require written approval.";
export function chatLanguage(messages: ChatMessage[], preferred?: unknown): ChatLanguage {
  const last = [...messages].reverse().find(m => m.role === "user")?.content || "";
  if (/[\u0600-\u06ff]/.test(last)) return "fa";
  if (/\b(svenska|pris|kostar|företag|hemsida|hjälp|hej|tack|jag|vill)\b/i.test(last)) return "sv";
  if (preferred === "fa" || preferred === "sv" || preferred === "en") return preferred;
  return "en";
}
export function contactIntent(text: string) {
  return /[\w.+-]+@[\w.-]+\.[a-z]{2,}|(?:\+?\d[\d ()-]{7,}\d)|contact|consultation|human|register|save my|book|تماس|مشاوره|ثبت|رزرو|ایمیل|شماره|kontakt|boka|offert|mejl/i.test(text);
}
export function knownName(messages: ChatMessage[]) {
  const user = messages.filter(m => m.role === "user").map(m => m.content).join("\n");
  return user.match(/(?:my name is|jag heter|اسم من|نام من|اسمم|نامم)\s*[:：]?\s*([^\n,.!?؟،@]{2,60})/i)?.[1]?.trim() || "";
}
export function guideReply(messages: ChatMessage[], language: ChatLanguage) {
  const last = messages.at(-1)?.content || "";
  const q = last.toLowerCase();
  const name = knownName(messages);
  const choose = (en: string, sv: string, fa: string) => ({en,sv,fa}[language]);
  if (/what.*name|my name|vad.*heter|اسمی|اسمم|اسم من|نام من|اسم.*چی|نام.*چی/.test(q)) return name ? choose(`You introduced yourself as ${name}. Your contact details have not been saved as an enquiry. Use “Request contact” if you want ELORNA to follow up.`, `Du presenterade dig som ${name}. Kontaktuppgifterna är ännu inte sparade som en förfrågan. Välj ”Begär kontakt” för uppföljning.`, `در این گفتگو خودت را «${name}» معرفی کردی. اطلاعات تماس هنوز به‌عنوان درخواست ثبت نشده است؛ برای پیگیری، «درخواست تماس» را انتخاب کن.`) : choose("You haven’t introduced yourself by name in this conversation yet. What should I call you?", "Du har inte angett ditt namn i den här konversationen ännu. Vad heter du?", "هنوز نامت را در این گفتگو مشخص نکرده‌ای. دوست داری چه نامی صدایت کنم؟");
  if (/price|pricing|cost|قیمت|هزینه|pris|kost/.test(q)) return choose("Indicative prices: Essential 3,500–6,000 SEK; Business 7,500–14,000; three-language site 12,000–22,000; store 18,000–32,000; AI Starter 6,500–15,000; consultation 500 SEK/hour. Applicable taxes and third-party costs are itemised in your quote. What type of project and budget do you have?", "Vägledande priser: Essential 3 500–6 000 SEK; Business 7 500–14 000; trespråkig webbplats 12 000–22 000; butik 18 000–32 000; AI Starter 6 500–15 000; rådgivning 500 SEK/timme. Skatt och externa kostnader anges i offerten. Vilken typ av projekt och budget har du?", "بازه‌های پیشنهادی: سایت ساده ۳٬۵۰۰ تا ۶٬۰۰۰ کرون؛ سایت کسب‌وکار ۷٬۵۰۰ تا ۱۴٬۰۰۰؛ سه‌زبانه ۱۲٬۰۰۰ تا ۲۲٬۰۰۰؛ فروشگاه ۱۸٬۰۰۰ تا ۳۲٬۰۰۰؛ AI ساده ۶٬۵۰۰ تا ۱۵٬۰۰۰؛ مشاوره ساعتی ۵۰۰ کرون. مالیات و هزینه‌های جانبی در پیشنهاد کتبی مشخص می‌شوند. چه نوع پروژه و بودجه‌ای داری؟");
  if (contactIntent(last)) return choose("I can help you prepare a contact request. Details typed in chat are not automatically saved to the CRM. Open “Request contact”, review your details and consent, then submit. You’ll receive a reference only after successful storage.", "Jag kan hjälpa dig förbereda en kontaktförfrågan. Uppgifter i chatten sparas inte automatiskt i CRM. Öppna ”Begär kontakt”, granska uppgifterna och ditt samtycke och skicka. Du får ett referensnummer först när lagringen har lyckats.", "می‌توانم برای درخواست تماس کمکت کنم. اطلاعاتی که در چت می‌نویسی خودکار در CRM ثبت نمی‌شوند. «درخواست تماس» را باز کن، اطلاعات و رضایتت را بررسی کن و ارسال کن. فقط پس از ذخیره موفق، شماره پیگیری می‌گیری.");
  if (/capital|fund|سرمایه|kapital/.test(q)) return choose("Start with CAPITAL readiness: 1. Organise your business model and finances. 2. Collect real evidence of traction. 3. Prepare a clear overview for future investor conversations. ELORNA does not guarantee funding. Which documents do you already have?", "Börja med CAPITAL: 1. Strukturera affärsmodell och ekonomi. 2. Samla verkliga bevis på utveckling. 3. Förbered ett tydligt underlag inför investerarsamtal. Finansiering garanteras inte. Vilka underlag har du?", "برای آمادگی سرمایه، سه قدم عملی: ۱. مدل کسب‌وکار و اطلاعات مالی را منظم کن. ۲. شواهد واقعی پیشرفت را جمع کن. ۳. معرفی روشن برای گفتگو با سرمایه‌گذار آماده کن. تأمین سرمایه تضمین نمی‌شود. الان چه مدارکی آماده داری؟");
  if (/grow|رشد|väx/.test(q)) return choose("GROW can help: 1. Choose one measurable goal. 2. Review traffic, enquiries and sales to find the bottleneck. 3. Test one change and compare the results. Which metric do you want to improve?", "GROW kan hjälpa: 1. Välj ett mätbart mål. 2. Granska trafik, förfrågningar och försäljning. 3. Testa en ändring och jämför resultaten. Vilket mått vill du förbättra?", "برای رشد: ۱. یک هدف قابل‌اندازه‌گیری انتخاب کن. ۲. بازدید، درخواست‌ها و فروش را برای یافتن مانع بررسی کن. ۳. یک تغییر را آزمایش و نتیجه را مقایسه کن. کدام معیار را می‌خواهی بهتر کنی؟");
  if (/sell|sales|فروش|sälj/.test(q)) return choose("For SELL: 1. Define the offer and intended customer. 2. Map their path from first visit to enquiry or purchase. 3. Measure where they drop out. Where do customers usually find you today?", "För SELL: 1. Definiera erbjudande och målgrupp. 2. Kartlägg vägen från besök till förfrågan eller köp. 3. Mät var kunderna avbryter. Var hittar kunder dig idag?", "برای فروش: ۱. پیشنهاد و مشتری هدف را مشخص کن. ۲. مسیر بازدید تا درخواست یا خرید را ترسیم کن. ۳. نقطه ریزش را اندازه بگیر. الان مشتری‌ها از کجا تو را پیدا می‌کنند؟");
  if (/website|web|store|shop|سایت|فروشگاه|hemsida|webb/.test(q)) return choose("For a website, first agree the pages, languages and key functions. A simple one-page site starts at 3,500 SEK; a store has a different scope. Do you need a service website, bookings or product sales?", "För en webbplats börjar vi med sidor, språk och funktioner. En enkel sida börjar på 3 500 SEK; en butik har annan omfattning. Behöver du presentation, bokning eller produktförsäljning?", "برای سایت، ابتدا تعداد صفحات، زبان‌ها و امکانات را مشخص می‌کنیم. سایت تک‌صفحه‌ای از ۳٬۵۰۰ کرون شروع می‌شود؛ فروشگاه محدوده متفاوتی دارد. معرفی خدمات می‌خواهی، رزرو یا فروش محصول؟");
  if (/build|idea|شروع|ایده|start|börja/.test(q)) return choose("Start with BUILD: 1. Identify the customer and problem. 2. Shape one clear offer. 3. Plan a small first launch. What is your idea and who will use it?", "Börja med BUILD: 1. Identifiera kund och problem. 2. Forma ett tydligt erbjudande. 3. Planera en liten första lansering. Vad är din idé och vem ska använda den?", "برای شروع: ۱. مشتری و مسئله را مشخص کن. ۲. یک پیشنهاد روشن بساز. ۳. اولین راه‌اندازی کوچک را برنامه‌ریزی کن. ایده‌ات چیست و برای چه کسی است؟");
  if (/^(hi|hello|hej|سلام|درود)[! .؟]*$/.test(q)) return choose("Hello! Would you like help with a website, AI automation, sales or pricing?", "Hej! Vill du ha hjälp med webbplats, AI-automation, försäljning eller priser?", "سلام! برای طراحی سایت، خودکارسازی با AI، فروش یا قیمت‌ها کمک می‌خواهی؟");
  if (/thank|tack|مرسی|ممنون/.test(q)) return choose("You’re welcome. You can continue this conversation or send a contact request when you are ready.", "Tack själv. Du kan fortsätta samtalet eller skicka en kontaktförfrågan när du är redo.", "خواهش می‌کنم. هر وقت آماده بودی می‌توانی گفتگو را ادامه بدهی یا درخواست تماس ارسال کنی.");
  const users = messages.filter(m => m.role === "user");
  const project = users.slice(0,-1).find(m => /website|store|سایت|فروشگاه|webb|hemsida/.test(m.content.toLowerCase()));
  if (project) return choose(`Earlier you mentioned “${project.content.slice(0,120)}”. To narrow that project down, how many pages or products and which languages do you need?`, `Tidigare nämnde du ”${project.content.slice(0,120)}”. Hur många sidor eller produkter och vilka språk behöver projektet?`, `قبلاً گفتی «${project.content.slice(0,120)}». برای مشخص‌کردن همان پروژه، چند صفحه یا محصول و چه زبان‌هایی نیاز داری؟`);
  return users.length < 3 ? choose("I’m currently using ELORNA’s service guide. I can explain websites, automation, pricing and our four business stages. Which would you like to explore?", "Jag använder just nu ELORNAs tjänsteguide. Jag kan förklara webbplatser, automation, priser och våra fyra steg. Vad vill du veta mer om?", "در حال حاضر از راهنمای خدمات ELORNA استفاده می‌کنم. می‌توانم درباره سایت، خودکارسازی، قیمت و مراحل کسب‌وکار راهنمایی کنم. کدام موضوع برایت مهم‌تر است؟") : choose("The service guide cannot resolve that specific question reliably. Please describe your intended result, or use “Request contact” to ask Elnaz directly. I haven’t saved a request or scheduled a meeting.", "Tjänsteguiden kan inte besvara just den frågan säkert. Beskriv resultatet du vill uppnå eller välj ”Begär kontakt” för att fråga Elnaz. Ingen förfrågan eller mötestid har registrerats.", "راهنمای خدمات نمی‌تواند این پرسش مشخص را با اطمینان حل کند. نتیجه‌ای که می‌خواهی را توضیح بده یا با «درخواست تماس» از الناز بپرس. هنوز درخواست یا جلسه‌ای ثبت نشده است.");
}
